### ISSUE TITLE
Options to bolster inclusivity

### ISSUE THREAD

**Issue by jquarshi** [ThetaTau/CMT#539]
As a user, being able to collect things such as pro nouns, or Race would allow me to collect data for the future on diversity.

_Acceptment Criteria_

- Brothers and Alumni can add/remove/edit pronouns and edit their chosen race. 
- For Brothers that do have pronouns, those pronouns will appear under their name in the CMT
- Race will not be displayed under each member but will appear in a pie chart on the CMT landing.

**Comment by VenturaFranklin** [comment]
The pledge form is now collecting this. We should add the form to the user page as well for members that want to go back and add that information
