### ISSUE TITLE
preferred name

### ISSUE THREAD

**Issue by VenturaFranklin** [ThetaTau/CMT#541]
can we put in a "preferred name" field into the profile? While John is my first name, I obviously go by my middle name instead.

**Comment by VenturaFranklin** [comment]
Add the field to the model and then add to Pledge form, and user page.

**Comment by Gumby9694** [comment]
Should the "Nickname" field be removed? Both a preferred name field and a nickname field seem redundant.

**Comment by VenturaFranklin** [comment]
Here is a good breakdown on difference: https://www.wikitree.com/wiki/Help:Name_Fields#Specific_Rules_for_Individual_Name_Fields
