### ISSUE TITLE
Workflow Reminders & Clean up

### ISSUE THREAD

**Issue by VenturaFranklin** [ThetaTau/CMT#594]
Send periodic reminders to assigned officer of workflow to complete the tasks. 
Clear out old workflows that have been around for too long.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT What are your thoughts on the frequency of reminder emails for tasks and when should they start (5 days after first email? longer? depending on task?) These are workflows where officers have to approve or do something, ie. Disciplinary, resignation, osm, convention
Also, we have quite a few tasks that have not been completed. Should we have a regular semester clean up or every task before X date is cleaned out?

**Comment by jimgaffneyTT** [comment]
I think delete every task from before 8.1.2021.

For frequency, I think it really depends on the task.  Some, like MSCR's and other mission-critical things need at least weekly past the due date.  Others, not so much.
