### ISSUE TITLE
Goal Tracker

### ISSUE THREAD

**Issue by jimgaffneyTT** [ThetaTau/CMT#623]
I want to talk about the idea of building a tracker for individual and chapter conduct, this would be an interface for H&S committee members and CO staff to use, not student members or other Natoffs. We can talk through this when you have freetime.

This just came up tonight on the H&S call, why I didn't bring it up during our call today.

**Comment by VenturaFranklin** [comment]
Actionable items that need to be done, when all complete also add to notes so there is one place to add
Can the tasks and then notes nest? So actions related and then sent to the same note
Chapter can see the tasks, does not need to. First needed for natoff
- When due notification to chapter/member
SMART
H&S filter

**Comment by VenturaFranklin** [comment]
This was repurposed from the disciplinary tracker into Goals
#757 was created to replace
