### ISSUE TITLE
Move the Semester Report (the uploaded paper document) Into it's own Form

### ISSUE THREAD

**Issue by jimgaffneyTT** [ThetaTau/CMT#629]
We're still running into the inability to run a clean report of which chapters have submitted their semester report pdf; it's getting mixed up in chapters updating their address or website or whatever.  Can we move the upload into it's own form so that we can track it independently?

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT  Now a chapter only submits the semester report at: http://cmt.thetatau.org/report
If they need to update the chapter information they should do that on their respective chapter page.
The report list should be correct as well now: https://cmt.thetatau.org/forms/report-list/
