### ISSUE TITLE
Update to Initiation Process

### ISSUE THREAD

**Issue by jimgaffneyTT** [ThetaTau/CMT#635]
**_I'll explain all of this on our call this afternoon, but wanted to get it in writing too._**

We're changing the way we order badges from Herff Jones in January, so we can use this as an opportunity to cut a few steps out of the initiation process.

What the members input will be the same; they'll still indicate which badge their initiates will order.

When we sync the data to QuickBooks, however, we **only want to be syncing the initiation fee, not the badge/guard costs.**

When we mark the invoice as paid, we'd like the shingle csv to be automatically emailed to goosecreekpublishing@yahoo.com and we'd like the invoice CSV (which would still include the badge and guard info) to be sent to central.office@thetatau.org.   We'd also like an email sent to the chapter officers with instructions on how to order their badges directly from Herff.  These written instructions are forthcoming. The chapters will then login to a Herff Jones website and order/pay for the jewelry themselves.

So the steps would be:

1. Chapter inputs data
2. We sync the invoice to QB
3. The invoice is marked paid, auto-emails are sent, and the process is then complete.

**Comment by VenturaFranklin** [comment]
Initiation process all attached to same email

Make clear - Action Required - Init pro
