### ISSUE TITLE
Initiation 1687

### ISSUE THREAD

**Issue by jimgaffneyTT** [ThetaTau/CMT#646]
Initiation process 1687 is stuck and won't sync to QB.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT The guard type 0800s does not exist in quickbooks.
It looks like it should be One Etched plated : https://cmt.thetatau.org/inH&Tforms/guard/4/change/
The code for each item here: https://cmt.thetatau.org/inH&Tforms/guard/
Should match a Name of an item in quickbooks.
