### ISSUE TITLE
View paid invoices

### ISSUE THREAD

**Issue by VenturaFranklin** [ThetaTau/CMT#703]
Would like to be able to see paid invoices as well as unpaid 
- CCs have questions re: whether invoices came, what they look like, etc.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT I can't remember why we didn't do this in the first place.

**Comment by jimgaffneyTT** [comment]
I can't either, and I'm fine with it.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT Add comment that old invoices text

**Comment by jimgaffneyTT** [comment]
All of your chapter's invoices are listed below, both paid and unpaid.

Paid invoices that were issued after 2021 will have a link to the paid invoices.  Older paid invoices will not be listed below.  If you need a copy of an older invoice, please contact the Central Office.
