### ISSUE TITLE
Verify PPM education

### ISSUE THREAD

**Issue by VenturaFranklin** [ThetaTau/CMT#725]
Date, which category, name and phone of facilitator

Process sent to CO and CCd RD, CO approve/deny.

Deny --> sent to chapter to resubmit

**Comment by VenturaFranklin** [comment]
Chapter Officers (or Risk Management Chair) will organize chapter participation at least once per year in each
of the following areas. The chapter’s university office of student affairs (or other similar department) likely has
information and/or facilitators for each of these areas:
● alcohol and drug awareness program to educate its members on the responsibilities and consequences of
alcohol consumption and drug use;
● anti-harassment program to assist members in recognizing, preventing, and reporting discrimination,
sexual harassment, and hazing;
● mental health recognition program (such as suicide or depression) to help members in the recognition of
warning signs, identification of referral resources, and skills to respond to members at-risk.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT please review the wording above

**Comment by jimgaffneyTT** [comment]
Chapter Officers (or Risk Management Chair) will organize chapter participation at least once per year in each
of the following areas. The chapter’s university office of student affairs (or other similar department) likely has
information and/or facilitators for each of these areas:
● alcohol and drug awareness program to educate its members on the responsibilities and consequences of
alcohol consumption and drug use;
● anti-harassment program to assist members in recognizing, preventing, and reporting discrimination,
sexual harassment, and hazing;
● mental health recognition program (such as suicide or depression) to help members in the recognition of
warning signs, identification of referral resources, and skills to respond to members at-risk.

These programs must be conducted by a qualified professional (eg. a campus police officer, a healthcare professional, a substance abuse counselor, etc) and that professional must provide a letter, on their letterhead, stipulating the training they provided.  They must also indicate the date and location of the training and the number of student members in attendance.

That form should be uploaded below. The Central Office will verify that the letter is acceptable and mark your programming requirement as completed.
