### ISSUE TITLE
Sync Paid Invoices

### ISSUE THREAD

**Issue by jimgaffneyTT** [ThetaTau/CMT#754]
It would be great if, after an initiation invoice is paid in QuickBooks, it could automatically sync back somehow so that the initiation workflow is then completed and the chapter is freed to order badges without my having to manually update invoices.

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT I set this to do pledge AND init. Let me know if this should not be the case.
**This depends on the invoice number being input by the user when the process is started.**
