### ISSUE TITLE
Chapter money balance details

### ISSUE THREAD

**Issue by anna-thilly** [ThetaTau/CMT#76]
**Is your feature request related to a problem? Please describe.**

It's nice that we can log in and see what the money balance of our chapter is, however it's annoying that I can't click on the balance and see more details (i.e. the history of how our balance has changed).  It's also unclear whether the balance is a credit to our account or the amount that we owe.

**Describe the solution you'd like**
I would like to be able to open the history/details of account balance and be able to clearly see what amounts are credits and what amounts are debits to our account. Ex. shows our history of payments

**Describe alternatives you've considered**
There doesn't seem to be anywhere that this information can be accessed.

GanttStart: 2020-08-01
GanttDue: 2020-08-02

**Comment by VenturaFranklin** [comment]
Thank you for your suggestion!
The central office is happy to send statements to chapters on request.

For my reference: We’d need the enterprise edition of QB for anything like that.

**Comment by VenturaFranklin** [comment]
We should maybe note this in the page that if you want a breakdown you can contact the central office.

**Comment by VenturaFranklin** [comment]
@anna-thilly This is complete. See https://cmt.thetatau.org/finances/
Thank you for the suggestion! Please provide more suggestions!
