### ISSUE TITLE
Notifications for Certain Accounts

### ISSUE THREAD

**Issue by jimgaffneyTT** [ThetaTau/CMT#760]
Is it possible to set up notifications to be sent to CO and, potentially others (like a trustee) when changes are made to certain user or chapter accounts?

Changes being, pledgings, initiations, pre-alums, etc.

**Comment by VenturaFranklin** [comment]
A great project to use: https://github.com/Salaah01/django-email-signals

**Comment by VenturaFranklin** [comment]
@jimgaffneyTT 
**Here is the list of user tables to watch. Meaning when the associated user matches you would get an update**

> users.models.User, users.models.UserStatusChange, users.models.UserRoleChange, forms.models.ReturnStudent, 

**Here is the list of chapter tables to watch. Meaning when the associated chapter matches you would get an update**

> chapters.models.Chapter, events.models.Event, submissions.models.Submission, forms.models.PledgeProgram, forms.models.PledgeProgramProcess, forms.models.Initiation, forms.models.Depledge, forms.models.ChapterReport, forms.models.HSEducation, forms.models.Audit, forms.models.Pledge,  forms.models.InitiationProcess, forms.models.PledgeProcess, forms.models.OSM, forms.models.Bylaws, tasks.models.TaskChapter,

**Here is both where matching on a user or matching on a chapter would generate an update**
> forms.models.PrematureAlumnus, forms.models.DisciplinaryProcess, forms.models.CollectionReferral, forms.models.ResignationProcess,

Do you want all of these? Can we reduce some of them?

Do you envision just watching one of them, or will it always be all of them?
eg. A chapter seems to be depledging a lot of pledges so from now on CO will get notified on every depledge? 
Or more like, 
chapter is in trouble so CO will get notified on any and every change that happens to any of the above for that chapter?
